# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "wonseok/auto-create-README" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files
        run: |
          # get the list of changed files from the pull request
          git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }} > changed_files.txt
          # set the output variable with the content of the file
          echo "::set-output name=files::$(cat changed_files.txt)"
      - name: Get folder path
        id: folder-path
        run: |
          # get the folder path from the list of changed files
          path=$(grep -o -m 1 '/.*' ${{ steps.changed-files.outputs.files }})
          path=$(dirname $path)
          # set the output variable with the folder path
          echo "::set-output name=path::${path}"
      - name: Generate README
        run: |
          # write script to generate README.md file in the specific folder with the pull request message
          touch ${{ steps.folder-path.outputs.path }}/README.md
          echo "This is a generated README file." > ${{ steps.folder-path.outputs.path }}/README.md
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Add README.md file'
          add: .
          author_name: 'GitHub Action'
          author_email: 'action@github.com'

